import { useState } from "react";
import { Check, Pencil } from "lucide-react";
import { SectionHeading, Card, Input, TextArea, Button, DemoTag } from "../components/ui";
import { useWorkspaceStore } from "../store/useWorkspaceStore";
import { OfferingPaymentLink } from "../features/company/OfferingPaymentLink";

export default function CompanyPage() {
  const company = useWorkspaceStore((s) => s.company)!;
  const updateCompany = useWorkspaceStore((s) => s.updateCompany);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(company);

  function startEdit() {
    setDraft(company);
    setEditing(true);
  }
  function save() {
    updateCompany(draft);
    setEditing(false);
  }

  return (
    <div className="space-y-6">
      <SectionHeading
        eyebrow={company.industry}
        title={company.name}
        description={company.tagline}
        action={
          editing ? (
            <Button onClick={save}><Check className="h-4 w-4" /> Save changes</Button>
          ) : (
            <Button variant="secondary" onClick={startEdit}><Pencil className="h-4 w-4" /> Edit</Button>
          )
        }
      />

      {company.isDemo && (
        <div className="flex items-center gap-2 rounded-xl border border-line bg-paper-dim px-4 py-2.5">
          <DemoTag />
          <span className="text-[13px] text-ink-faint">This company was generated by Mero's demo company builder.</span>
        </div>
      )}

      <Card className="p-6">
        <h2 className="font-display text-[16px] font-semibold text-ink">Overview</h2>
        <div className="mt-4 grid gap-5 sm:grid-cols-2">
          <Field label="Name">
            {editing ? <Input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /> : <p className="text-[14px] text-ink">{company.name}</p>}
          </Field>
          <Field label="Industry">
            {editing ? <Input value={draft.industry} onChange={(e) => setDraft({ ...draft, industry: e.target.value })} /> : <p className="text-[14px] text-ink">{company.industry}</p>}
          </Field>
          <Field label="Business model">
            {editing ? (
              <Input value={draft.businessModel} onChange={(e) => setDraft({ ...draft, businessModel: e.target.value as typeof draft.businessModel })} />
            ) : (
              <p className="text-[14px] capitalize text-ink">{company.businessModel}</p>
            )}
          </Field>
          <Field label="Tagline">
            {editing ? <Input value={draft.tagline} onChange={(e) => setDraft({ ...draft, tagline: e.target.value })} /> : <p className="text-[14px] text-ink">{company.tagline}</p>}
          </Field>
        </div>
        <div className="mt-5">
          <Field label="Description">
            {editing ? <TextArea rows={3} value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /> : <p className="text-[14px] leading-relaxed text-ink-soft">{company.description}</p>}
          </Field>
        </div>
        <div className="mt-5">
          <Field label="Target audience">
            {editing ? <TextArea rows={2} value={draft.targetAudience} onChange={(e) => setDraft({ ...draft, targetAudience: e.target.value })} /> : <p className="text-[14px] leading-relaxed text-ink-soft">{company.targetAudience}</p>}
          </Field>
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="font-display text-[16px] font-semibold text-ink">Brand</h2>
        <div className="mt-4 grid gap-5 sm:grid-cols-2">
          <Field label="Personality">
            <div className="flex flex-wrap gap-2">
              {company.brand.personality.map((p) => (
                <span key={p} className="rounded-full border border-line bg-paper-dim px-3 py-1 text-[12.5px] text-ink-soft">{p}</span>
              ))}
            </div>
          </Field>
          <Field label="Colors">
            <div className="flex gap-3">
              {company.brand.colors.map((c) => (
                <div key={c.name} className="flex items-center gap-2 rounded-full border border-line py-1 pl-1 pr-3">
                  <span className="h-6 w-6 rounded-full border border-line" style={{ background: c.hex }} />
                  <span className="text-[12.5px] text-ink-soft">{c.name}</span>
                </div>
              ))}
            </div>
          </Field>
        </div>
        <div className="mt-5">
          <Field label="Voice"><p className="text-[14px] leading-relaxed text-ink-soft">{company.brand.voice}</p></Field>
        </div>
        <div className="mt-5">
          <Field label="Logo concept"><p className="text-[14px] leading-relaxed text-ink-soft">{company.brand.logoConcept}</p></Field>
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="font-display text-[16px] font-semibold text-ink">Products & Services</h2>
        <div className="mt-4 space-y-3">
          {company.offerings.map((o) => (
            <div key={o.id} className="rounded-xl border border-line p-4">
              <div className="flex items-center justify-between">
                <p className="text-[14px] font-semibold text-ink">{o.name}</p>
                <span className="text-[13px] font-medium text-moss-600">{o.pricingConcept}</span>
              </div>
              <p className="mt-1 text-[13px] leading-relaxed text-ink-faint">{o.description}</p>
              <p className="mt-1.5 text-[12px] text-ink-faint/80">Positioning: {o.positioning}</p>
              <OfferingPaymentLink offering={o} />
            </div>
          ))}
        </div>
      </Card>

      <Card className="p-6">
        <h2 className="font-display text-[16px] font-semibold text-ink">Goals</h2>
        <div className="mt-4 grid gap-4 sm:grid-cols-2">
          <Field label="Launch goal"><p className="text-[14px] text-ink-soft">{company.goalSummary.launch}</p></Field>
          <Field label="Customer goal"><p className="text-[14px] text-ink-soft">{company.goalSummary.customer}</p></Field>
          <Field label="Revenue goal"><p className="text-[14px] text-ink-soft">{company.goalSummary.revenue}</p></Field>
          <Field label="Growth goal"><p className="text-[14px] text-ink-soft">{company.goalSummary.growth}</p></Field>
        </div>
      </Card>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="mb-1.5 text-[12px] font-medium uppercase tracking-wide text-ink-faint">{label}</p>
      {children}
    </div>
  );
}
